### PR TITLE
chore: Add @DavidPHirsch as member

### PR DESCRIPTION
**Pull request by DavidPHirsch**
## This PR
adds @DavidPHirsch as member in MAINTAINERS

### CODE REVIEW

**Comment by DavidPHirsch** [comment]
linking https://github.com/keptn/community/issues/162#issuecomment-1226980179

**Review by thisthat — APPROVED** [review]

**Review by thschue — DISMISSED** [review]
lgtm

**Comment by thisthat** [comment]
Hey @DavidPHirsch could you please update the PR signing your commit and rebasing?

**Review by oleg-nenashev — APPROVED** [review]
I manually approved the DCO

**Pull request merged**
