### PR TITLE
fix: add support for ingress class name

### LINKED ISSUE #7323: control-plane ingress is missing ingressClassName support
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS (e.g., Linux, macOS, Windows): N/A
* Keptn Version (`keptn version`): N/A
* Kubernetes Cloud Provider (e.g., GKE, AKS): N/A
* Kubernetes version (`kubectl version`): N/A

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [x] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
Newer ingress objects and ingress controller only listen for ingressClassName (instead of the deprecated annotation)

**To Reproduce**
N/A

**Expected behavior**
Should provide ingressClassName.

**Current behavior**
Does not

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by jetersen**
## This PR
- adds ingressClassName to control plane ingress

### Related Issues

Fixes #7323

### CODE REVIEW

**Review by thisthat — APPROVED** [review]
LGTM, thank you for your contribution @jetersen

**Comment by jetersen** [comment]
@thisthat I take it that the chart is deployed together with everything else so no need for me to bump the version? 🤔

**Comment by thisthat** [comment]
Yes, no need to bump it! We generate the version in our pipeline automatically at release :)

**Comment by jetersen** [comment]
Thanks for accepting our contribution, much appreciated 👏

**Pull request merged**
