### PR TITLE
chore: Add @oleg-nenashev to the list of contributors

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Signed-off-by: Oleg Nenashev <o.v.nenashev@gmail.com>

## This PR

- adds this new feature

### Related Issues

Fixes #1234523

### CODE REVIEW

**Review by johannes-b — DISMISSED** [review]
lgtm

**Comment by thisthat** [comment]
Hi @oleg-nenashev thank you for the PR. Due to some limitations of GitHub, if you have only one commit it must follow our Semantic Convention for PR titles. Could you please run `git commit --amend --signoff` and change the message to `chore: Add @oleg-nenashev to the list of contributors`?

**Comment by oleg-nenashev** [comment]
@thisthat yeah I saw the status yesterday but my assumption was that it is not a blocker for PRs that will be skipped in the changelog anyway. Should be fixed now

**Review by johannes-b — COMMENTED** [review]
lgtm

**Review by thisthat — APPROVED** [review]

**Pull request merged**
