### PR TITLE
Set git upstream url via project settings page

### PR DESCRIPTION
**Pull request by laneli**
Implements #3417 
* The text and link for git upstream configuration changed:
image

* There is a new project settings page containing the git upstream form
image

* Validation and disabling of button is build in accordingly
image

* If a user already has an upstream url set, the data is loaded and displayed in the form
* The token field is filled with placeholder data and emptied on focus
image

### CODE REVIEW

**Comment by Kirdock** [comment]
We should re-think our `http-error-interceptor`. Currently if an error happens, we retry it up to 3 times, which is not needed in this case because there is some server-side validation (invalid URL, username not found, etc.) that may cause it.

We can at least check if the provided URL is valid client-side

**Review by ermin-muratovic — APPROVED** [review]
lgtm

**Comment by laneli** [comment]
@Kirdock can you file a new issue for the http-interceptor?

**Comment by Kirdock** [comment]
> @Kirdock can you file a new issue for the http-interceptor?

done. Issue: #3950

**Pull request merged**
