### PR TITLE
#4540 Helm-Service Adjust primary service labels for more consistency

### PR DESCRIPTION
**Pull request by tolleiv**
See related issue #4540 - this adds the `-primary` suffix for the labeled service to be consistent with the modifications of the pod labels. This won't change any behavior within the Kubernetes cluster, the labels are usually not referenced in ServiceMesh components.

Signed-off-by: Tolleiv Nietsch <github@tolleiv.de>

### CODE REVIEW

**Review by warber — COMMENTED** [review]
thx, lgtm

**Review by warber — APPROVED** [review]

**Comment by dyladan** [comment]
[CLA assistant check](https://cla.oss.dynalabs.io/keptn/keptn?pullRequest=4541) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.oss.dynalabs.io/keptn/keptn?pullRequest=4541) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.oss.dynalabs.io/check/keptn/keptn?pullRequest=4541) it.</sub>

**Comment by tolleiv** [comment]
> [CLA assistant check](https://cla.oss.dynalabs.io/keptn/keptn?pullRequest=4541)
> Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.oss.dynalabs.io/keptn/keptn?pullRequest=4541) before we can accept your contribution.
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.oss.dynalabs.io/check/keptn/keptn?pullRequest=4541) it.

The CLI link is responding with HTTP 502 :( - the CLA is btw .not mentioned in the contributions guidelines

**Comment by tolleiv** [comment]
I've signed to CLA and adjusted the related unit tests.

**Review by warber — APPROVED** [review]

**Pull request merged**
