### PR TITLE
fix(bridge): Corrected misleading message in creating project

### LINKED ISSUE #8106: Improve message in Bridge (0.16.0) when creating a new project
image

Message reads:

> Your project needs a Shipyard. Add a file from your filesystem or drag & drop it here it add it to your project.

I think it should be 

> Your project needs a Shipyard. Add a file from your filesystem or drag & drop it here **to** add it to your project.

Relevant code:
https://github.com/keptn/keptn/blob/258c5a603498ef89d7c563298c68b9b273ec4a0f/bridge/client/app/_components/ktb-project-settings/ktb-project-settings-shipyard/ktb-project-settings-shipyard.component.html#L4-L7

### PR DESCRIPTION
**Pull request by mehabhalodiya**
Signed-off-by: mehabhalodiya <mehabhalodiya@gmail.com>

## This PR

- correct message reads when creating a new project

### Related Issues

Fixes #8106

### CODE REVIEW

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM

**Comment by thisthat** [comment]
Hey @mehabhalodiya, thank you for the PR :) There is a limitation where if a PR has a single commit, it must follow the semantic PR naming schema :( Could you please change the commit message to the PR title? You can do that by running `git commit --amend -sm "fix(bridge): Corrected misleading message in creating project"`

**Comment by mehabhalodiya** [comment]
> Hey @mehabhalodiya, thank you for the PR :) There is a limitation where if a PR has a single commit, it must follow the semantic PR naming schema :( Could you please change the commit message to the PR title? You can do that by running git commit --amend -sm "fix(bridge): Corrected misleading message in creating project"

@thisthat Done. Thank you!

**Review by mowies — APPROVED** [review]
LGTM!

**Review by StackScribe — COMMENTED** [review]
How about linking "Shipyard" to the reference page, https://keptn.sh/docs/0.17.x/reference/files/shipyard/ ?

**Pull request merged**
