### PR TITLE
chore: Suggestion on making lifecycle toolkit more prominent

### PR DESCRIPTION
**Pull request by grabnerandi**
## This PR
As discussed with @thschue - wanted to put Keptn Lifecycle Toolkit into the spotlight on the readme!

### CODE REVIEW

**Review by thschue — CHANGES_REQUESTED** [review]
Looks good, the only thing I'd change is to keep the Keptn heading and its badges on the top and afterward proceed with the "Keptn Today! Lifecycle Toolkit Tomorrow!"

**Comment by grabnerandi** [comment]
@thschue - looks better now?

**Review by thschue — COMMENTED** [review]
some last suggestions ...

**Comment by thschue** [comment]
lgtm

**Review by thschue — APPROVED** [review]

**Pull request merged**
