### PR TITLE
#1499 fixed order of SLOs in evaluation

### LINKED ISSUE #1499: Sort the SLOs names in the Keptn Bridge Evaluation done results
**Is your feature request related to a problem? Please describe.**
Not a problem, just cosmetic

**Describe the solution you'd like**
Sort the SLO names to allow the results review to be consistent.

**Describe alternatives you've considered**
None

**Additional context**
current view:
image

### PR DESCRIPTION
**Pull request by Kirdock**
Fixes #1499 
Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>
image

### CODE REVIEW

**Comment by ermin-muratovic** [comment]
@Kirdock can you please add a screenshot of the result, like in the issue?

**Comment by Kirdock** [comment]
@ermin-muratovic done

**Comment by johannes-b** [comment]
image

**Review by johannes-b — APPROVED** [review]
lgtm

**Pull request merged**
