### PR TITLE
Core components

### PR DESCRIPTION
**Pull request by bacherfl**
- Added event-broker
- Added onboarding tool
- Added additional script to setup knative and knative-based core components (event-broker and channels)
- Disabled deployment of sockshop
- Disabled sockshop-specific configuration of Ansible Tower

### CODE REVIEW

**Comment by AloisReitbauer** [comment]
As we will release onboarding before knative support can we, for the time being, have two duplicate scripts for environment creation?

**Comment by bacherfl** [comment]
We can, although part of the onboarding is also the creation of the web hooks in the GitHub repos of the onboarded app. Since those point to the knative based event-broker there is currently a dependency to that part of the setup.

**Comment by johannes-b** [comment]
This PR will not be approved as long as travis does not validate it beforehand. 
I will work on this issue: https://github.com/keptn/keptn/issues/25

**Comment by johannes-b** [comment]
I close this PR since the Travis CI integration just works on new PRs.

**Pull request closed without merging**
