### PR TITLE
Add 1.19 to Travis and CLI Supported Versions

### PR DESCRIPTION
**Pull request by daviddyball**
Addresses parts of #2411 (unsure about docs updates)

### CODE REVIEW

**Review by christian-kreuzberger-dtx — APPROVED** [review]
lgtm

**Comment by johannes-b** [comment]
@christian-kreuzberger-dtx should we provide a backport to 0.6.2?

**Comment by christian-kreuzberger-dtx** [comment]
Yes, I'll handle the backport

**Comment by johannes-b** [comment]
@daviddyball many thanks for the PR. I will take care of the docs.

**Pull request merged**
