### PR TITLE
#2505 Remove version check for root cmds

### PR DESCRIPTION
**Pull request by pedroandrade**
Hey guys, this PR contains:
- Addi 5 seconds of a timeout to avoid hanging connection
- Remove version check for root calls

@christian-kreuzberger-dtx  @warber 

FIxing #2505

### CODE REVIEW

**Comment by christian-kreuzberger-dtx** [comment]
Looks like unit tests are not working

**Comment by warber** [comment]
@christian-kreuzberger-dtx @pedroandrade like so often, **global state is evil**! The unit test works in isolation but fails when executed together with all other tests, as some of them are fiddling around with the `checkEndPointStatusMock` variable.

Setting the variable to `false` before and resetting it to its old state after the test fixes the test.
This obviously is not a  fix for the actual problem - This would be: don't use global state variables at all...

I'll open create an issue for this.

**Comment by pedroandrade** [comment]
@christian-kreuzberger-dtx and @warber yeah, you're right guys, global state variable is very bad, so for this PR I will set the checkEndPointStatusMock as false to make tests pass properly, but to avoid this behavior, I've got a proposal, and if you like, you can assign to me the new issue, so

it's just a draft:

```code
type Option func(*Options)
type Options struct {
	Timeout time.Durtion
}

func WithTimeout(timeout time.Durtion) Option {
	return func(o *Options) {
		o.Timeout = timeout
	}
}

Type KeptnRequester interface {
  HealthCheck(ctx context.Context, endpoint string) error
}

type KeptnRequest struct {
	Options       Options
}

func NewKeptnRequest(options ...Option) *NewKeptnRequest {
  //Setup default values
	opt := Options{
		Timeout: 5 * time.Second,
	}
  
	for _, o := range options {
		o(&opt)
	}

	return &NewKeptnRequest{Options: opt}
}

```
and.. about the tests, we just mock the interface via dependency injection and avoid the global state vars even for timeout.

what do you think?

**Review by bacherfl — APPROVED** [review]
lgtm

**Pull request merged**
