### PR TITLE
chore: Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by vmasch**
add RSG as adopter

### CODE REVIEW

**Comment by warber** [comment]
Hi @vmasch Thanks for your contribution. In order to accept/merge your changes, you need to _sign off_ your commit(s). Please see the **DCO** Bot Details for instructions on how to do that. thx

**Comment by johannes-b** [comment]
Hello @vmasch 
can I ask you to sign your commits please. The instructions you find here: https://github.com/keptn/keptn/pull/4167/checks?check_run_id=2667909804

**Comment by dyladan** [comment]
[CLA assistant check](https://cla.oss.dynalabs.io/keptn/keptn?pullRequest=4167) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.oss.dynalabs.io/keptn/keptn?pullRequest=4167) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.oss.dynalabs.io/check/keptn/keptn?pullRequest=4167) it.</sub>

**Comment by mowies** [comment]
@vmasch is this PR still valid?
(just the commit signoff is missing for this to be mergable, see [the previous comment](https://github.com/keptn/keptn/pull/4167#issuecomment-851916004))

**Pull request closed without merging**
