### PR TITLE
feat(cli): Remove legacy code responsible for shipyard file upgrade

### LINKED ISSUE #5992: Core: Remove legacy update code
## Action Item 

Remove legacy code in the CLI that handles the upgrade of shipyard definition from 0.7.x.

### PR DESCRIPTION
**Pull request by odubajDT**
Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- remove legacy code responsible for shipyard file upgrade from version 0.1.* to 0.2.0 when using `keptn upgrade project ...`

### Related Issues

Fixes #5992

### CODE REVIEW

**Comment by odubajDT** [comment]
This should be also edited/deleted https://github.com/keptn/keptn/tree/master/bridge/client/app/_components/ktb-project-tile, but it should be done by someone with GUI knowledge.

**Review by mowies — APPROVED** [review]
LGTM

**Comment by mowies** [comment]
@odubajDT do we already have a ticket for the frontend part of this ticket?

**Comment by odubajDT** [comment]
> @odubajDT do we already have a ticket for the frontend part of this ticket?

I don't think so, I can create one.

**Comment by odubajDT** [comment]
Issue for bridge: https://github.com/keptn/keptn/issues/6211

**Review by mowies — APPROVED** [review]

**Comment by odubajDT** [comment]
Thanks to @mowies now we know that using fork in PR, docker login step is not done to secure the docker secret, create a new PR: https://github.com/keptn/keptn/pull/6270. @thisthat a quick check?

**Pull request closed without merging**
