### PR TITLE
#2478 Added SLI evaluation breakdown as barista table

### PR DESCRIPTION
**Pull request by johannes-b**
Signed-off-by: Patrick Hofmann <git@hfmnn.com>

### CODE REVIEW

**Comment by johannes-b** [comment]
To test the image, you can use the image: `docker.io/keptn/bridge2:0.8.1-dev-PR-2957.202101211948` (on a Keptn 0.8.0-alpha installation)

image

Open issues on the PR are: 

- [ ] Table does not refresh when clicking on the heatmap

- [ ] Fixed size of columns (name 55%, result 10%, value 10%, score 10%, criteria 15%), at least the `Name` needs more space

- [ ] Column `Score` shows the weight but should be translated into points between 0 and 100

- [ ] Split of criteria in warning/pass (currently just the pass criteria are shown)
  - [ ] show warning criteria

- [ ] Mark criteria as red (or with an icon as indicator) when a criteria failed

**Comment by pahofmann** [comment]
Hi @johannes-b,
the issues are all clear. I already added a few commits to fix the column width, score calculation and sorting. I hope to tackle the rest next week.

Not entirely sure on how to update this PR. Should I to a PR from my branch to [keptn/keptn/feature/2478/new-SLI-breakdown ](https://github.com/keptn/keptn/tree/feature/2478/new-SLI-breakdown)?

**Comment by johannes-b** [comment]
Hi @pahofmann 

thanks that you can address the points!

In the meantime, we have changed the GitHub action for PRs coming from outside the keptn repo. Please file a PR from your branch to keptn/master. Then I will close this one.

**Comment by christian-kreuzberger-dtx** [comment]
> In the meantime, we have changed the GitHub action for PRs coming from outside the keptn repo. Please file a PR from your branch to keptn/master. Then I will close this one.

You will need to rebase/merge keptn/keptn master branch for those GitHub actions to take effect. Also, @johannes-b , this will not publish the Docker Images.

**Comment by johannes-b** [comment]
This PR is not needed anymore since it is covered by: https://github.com/keptn/keptn/pull/3023

**Pull request closed without merging**
