### PR TITLE
#1863 Add support for multiple plans

### PR DESCRIPTION
**Pull request by supra08**
In this PR, I've added support for multiple plans such as an EKS installation, GCloud installation, or a local installation.
In this, if the user wants to use a different set of API credentials, he can specify them by using an environment variable `KEPTNCONFIG` that points to the creds JSON file location.
The command looks like this:
```
KEPTNCONFIG=./keptn_test_creds.json ./keptn add-resource --project=keptn07project 
```
As mentioned before, the creds will be stored in a JSON file. The fields would be:
* `api_token`
* `endpoint`

A sample JSON file would look like this:
```
{
    "api_token": "blahblah",
    "endpoint": "http://localhost:3000/api"
}
```

### CODE REVIEW

**Comment by ankitjain28may** [comment]
Hi @supra08 This is great, just a little suggestion, it would be great if we incorporate `KEPTNCONFIG` file lookup logic in credentialmanager itself rather adding in all the files as its a single point from where every command fetches auth credentials.

**Comment by supra08** [comment]
Yeah, I believe that's a better approach. I was working on the same in order to remove the code duplications.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks @ankitjain28may  and @supra08 , I was also going to comment on the duplications and whether we can centralize the approach. I'll take a look at the PR.

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM - this is awesome!

**Comment by ankitjain28may** [comment]
@christian-kreuzberger-dtx @supra08 The PR still lacks the logic for the support of Mac and windows.

**Pull request merged**
