### PR TITLE
#1278 Show latest deployment in stage overview

### PR DESCRIPTION
**Pull request by ermin-muratovic**
The list of stages now shows the image from the latest `sh.keptn.events.deployment-finished` on that stage and is linked if `deploymentURIPublic` is provided.

image

### CODE REVIEW

**Comment by johannes-b** [comment]
I like the enhancement. 
But I see no need for the information "2 Services" when I see the two tags. 
image

Besides, what does a tag show when just an onboarding but no deployment happened?

**Comment by ermin-muratovic** [comment]
> I like the enhancement.
> But I see no need for the information "2 Services" when I see the two tags.
> image
> 
> Besides, what does a tag show when just an onboarding but no deployment happened?

If the service is onboarded, but now deployment happened yet, then there will be no tags, just the information "x Services". 

I think that the information "x Services" makes sense, although it is redundant, because it's like a title to the tags. But it could also be omitted, if you think that it's "to much".

**Comment by christian-kreuzberger-dtx** [comment]
While I agree with @ermin-muratovic, I believe the information "x services" is not needed most of the time.
I vote for removing the "x services" information for now. Long term we should have an API endpoint that should return a list of services and whether an image has been deployed or not.

**Comment by ermin-muratovic** [comment]
I removed the "x services" title and removed the link to _deploymentURIPublic_. Clicking on the service-tag now will bring you to the root event and scroll to the specific stage. There you can inspect that deployment and if you want you will find there also the link to _deploymentURIPublic_ with the _sh.keptn.events.deployment-finished_-Event

**Pull request merged**
