### PR TITLE
increase buffer size on nginx

### LINKED ISSUE #4662: upstream sent too big header while reading response header from upstream error while SSO logout
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**

* Client OS: (e.g., Linux, macOS, Windows): Lonux
* Keptn Version (`keptn version`): 0.8.6
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE
* Kubernetes version (`kubectl version`): ??

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
Logout action results in http 502.
Bridge je setted to use SSO. 

**To Reproduce**

1. login
2. got to upper left corner and open menu
3. click logout

**Expected behavior**

User should be redirect to SSO system in which he can do logout.

**Current behavior**
User is not redirected to SSO service. Instead user land on error page (HTTP 502) generated by nginx. 

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by jskelin**
Close #4662

### CODE REVIEW

**Comment by warber** [comment]
hi, @jskelin pls also give an explanation of what was the problem and why we need this change :) thx

**Comment by jskelin** [comment]
In our environment we have SSO system that keptn bridge uses for authentication. In some casis when user try to do logout action, ngnix proxy returns http 502 error page. Looking in logs next message was found "upstream sent too big header while reading response header from upstream.....". 
That message indicates that buffer size is to small. Increasing buffer on our installation has resolved problem. 

More info:  https://ma.ttias.be/nginx-proxy-upstream-sent-big-header-reading-response-header-upstream/#:~:text=If%20the%20HTTP%20headers%20contain,configurations%20to%20your%20location%20block.

**Review by mowies — APPROVED** [review]
LGTM

**Comment by thisthat** [comment]
I think this closes #4662, right @jskelin?

**Pull request merged**
