### PR TITLE
feat: add labels to send events

### LINKED ISSUE #2126: Add labels parameter to all keptn send events
Labels are a powerful feature in Keptn. Right now you can pass them with [keptn send event start-evaluation](https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_send_event_start-evaluation/), but you can't do it for [keptn send event new-artifact](https://keptn.sh/docs/0.7.x/reference/cli/commands/keptn_send_event_new-artifact/)

**Idea:** It would be powerful to extend that CLI command as it will allow sending in labels such as `buildId`, which allows us to link the CI's `buildId` with the delivery process of Keptn. One of the major benefits is that the quality gate HeatMap can display the `buildId` instead of the timestamp

Here is an example for how I would like to send a new artifact event:
```
keptn send event new-artifact --project=keptn07project --service=simplenode --image=docker.io/grabnerandi/simplenodeservice --tag=1.0.0 --labels=buildId=101,sourceCi=Jenkins
```

These labels will then show up in the Keptn Bridge and will be used in the HeatMap (as proposed here #2131) to identify the evaluation run.

**Definition of Done:**
- [ ] The `keptn send event new-artifact` allows passing in labels by the `--lables` flag. See example above.

### PR DESCRIPTION
**Pull request by DarthBenro008**
- Fixes #2126

### CODE REVIEW

**Comment by christian-kreuzberger-dtx** [comment]
@warber I believe there is this a conflict with your recently merged changes. Can you advise on how to resolve the conflict?

**Comment by warber** [comment]
Hi, @DarthBenro008, the functionality inside `send_event_newArtifact.go`  has been completely moved to `trigger_delivery.go`.
Can you please rebase on the current master branch and apply your changes also to [trigger_delivery.go](https://github.com/keptn/keptn/blob/master/cli/cmd/trigger_delivery.go) ?

Note, that the code in [send_event_newArtifact.go](https://github.com/keptn/keptn/blob/master/cli/cmd/send_event_newArtifact.go) is marked as **deprecated** and will be removed in a future release. Currently, it is just [redirecting](https://github.com/keptn/keptn/blob/master/cli/cmd/send_event_newArtifact.go#L82) to the functionality implemented in `trigger_delivery.go`. Please make sure that the new, as well as the old command, supports this flag.

**Comment by DarthBenro008** [comment]
@warber thank you for the information, I will do the needful 😄

**Comment by DarthBenro008** [comment]
@christian-kreuzberger-dtx @warber I have done the needful and updated transferred the logic to `trigger_delivery.go` alongside labels redirect when invoked via `send_newArtifact`

**Review by warber — APPROVED** [review]
looks fine, thx

**Pull request merged**
