### PR TITLE
docs: add backwards-compatibility definition in compatibility requirements

### PR DESCRIPTION
**Pull request by Shiva953**
## This PR
This PR enhances the clarity of the Compatibility Requirements section in `VERSIONING.md` by adding a clear definition of backwards-incompatible change. This would help to clarify what types of changes are allowed in stable releases and what types of changes should be avoided.

### Related Issues
#9707

### CODE REVIEW

**Review by odubajDT — APPROVED** [review]

**Comment by odubajDT** [comment]
LGTM! Can you please adapt your commit message to `docs: add backwards-compatibility definition in compatibility requirements
` to pass the Semantic PR validation check? Thank you!

**Review by odubajDT — CHANGES_REQUESTED** [review]
Semantic PR validation

**Comment by mowies** [comment]
@Shiva953 this PR just needs a second empty commit for the semantic PR validation to become green

**Review by thisthat — COMMENTED** [review]
LGTM :) just please add an empty commit via `git commit --allow-empty -sm "fix semantic PR validation"`

**Review by odubajDT — APPROVED** [review]

**Review by thisthat — APPROVED** [review]

**Comment by thisthat** [comment]
Thanks for your contribution @Shiva953 , I'll merge the PR

**Pull request merged**
