### PR TITLE
fix(installer): Upgrade MongoDB to v11 since v10 is offline

### PR DESCRIPTION
**Pull request by czhujer**
## This PR
 - upgrades the MongoDB chart to v11.1.5
 - updates the values for mongo to conform to the new changes that came in with the update

### Related Issues

Fixes [#6605](https://github.com/keptn/keptn/issues/6605)

### Notes

It's based on PR https://github.com/keptn/keptn/pull/7444, but for keptn v13.x

### CODE REVIEW

**Comment by thisthat** [comment]
Hey @czhujer thank you for the contribution! could you please sign your commit with `git rebase HEAD~1 --signoff`? Thank you 😄

**Comment by czhujer** [comment]
> Hey @czhujer thank you for the contribution! could you please sign your commit with `git rebase HEAD~1 --signoff`? Thank you 😄

It's signed 👍

**Comment by mowies** [comment]
Hi @czhujer !
Could you explain why you did this change? Was there some issue?

**Comment by czhujer** [comment]
> Hi @czhujer ! Could you explain why you did this change? Was there some issue?

Hi @mowies , we're running Keptn 13.6 and after bitnami pruned its repo, old helm charts for mongodb are not accessible anymore..

**Comment by mowies** [comment]
Thanks for the explanation @czhujer , that makes a lot of sense then...
Do you have some reference where you got the update from Bitnami?

**Comment by czhujer** [comment]
@mowies https://github.com/bitnami/charts/issues/10539

**Review by mowies — CHANGES_REQUESTED** [review]
Thank you again for the contribution @czhujer !
For now I will block this PR. We will discuss internally some options on how to proceed in the future with Bitnami charts and what options we have to mitigate this and then I will get back to you. Hope that's fine for you :)

**Comment by mowies** [comment]
Update:
We decided to follow this strategy:
- Have the used helm dependencies baked into our repo together with the `Chart.lock` file. (this will help us release bugfix versions of Keptn, since we don't need to pull Mongo chart versions from bitnami anymore since everything is in our repo directly) (https://github.com/keptn/keptn/issues/8151)
- Create a pipeline that will remind us of new Mongo chart versions from time to time (https://github.com/keptn/keptn/issues/8148)

I hope this will also help you @czhujer , in fact the currently released Keptn versions (including your 0.13.6 version) should still work since the Mongo chart is directly inside our released chart tarballs already.

**Comment by czhujer** [comment]
hi @mowies 
thank you for quick response.
Yes, this will be also working solution.

**Comment by mowies** [comment]
Awesome! Then I will close this PR, thanks anyways for your contribution and for bringing this to our attention @czhujer!
Feel free to pick something different to contribute to Keptn or even one of the tickets above if you like :)

**Pull request closed without merging**
