### PR TITLE
#3538 back-navigation in evaluation-screen, fix order of SLIs

### LINKED ISSUE #3538: Provide better navigation from full screen evaluation screen
Right now there are two ways you can end up on the full screen evaluation screen
1: you get there by clicking on the full screen link out of the sequence or service view
2: you have a deep link to the full screen e.g: from your delivery pipeline

In both cases the user "is stuck" on that screen as there is no e.g: "back" link to the previous screen for option 2 - neither is there any good link to e.g: the sequence or service view of that evaluation

As discussed with @ermin-muratovic it would be great to enhance this navigation:
1: provide a link back to the sequence as shown in the screenshot below
2: allow to pass a parameter to the URL, e.g: ?returnUrl=https://yourkeptn/project/stage/sequendce/xxxx and then provide this link to "close" out the full screen

image

**Task:**
- On the evaluation screen, add a link to: `service`, `stage`, and `sequence`

**Definition of Done:**
- [ ] Update documentation screenshot here: https://keptn.sh/docs/0.8.x/reference/bridge/
- [ ] As a user, I can navigate to all main view (screens) the bridge is offering

### LINKED ISSUE #3851: Incorrect heatmap width when switching chart type
When selecting "Chart" and switching back to "Heatmap", the width of the heatmap changes
image

### PR DESCRIPTION
**Pull request by Kirdock**
Closes #3538 
Fixes #3851 
image

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

### CODE REVIEW

**Comment by johannes-b** [comment]
I will provide a review here.

**Review by ermin-muratovic — APPROVED** [review]
lgtm

**Comment by johannes-b** [comment]
- [ ] Click on "View service" opens wrong stage: 
image

**Comment by johannes-b** [comment]
- [ ] I would like to get the buttons better aligned and the info about the stage (see "Stage staging") moved to the top (see: "carts:0.11.1 in staging stage). @ermin-muratovic @laneli @Kirdock, do you have an opinion/improvement on my proposal? 

image

**Comment by Kirdock** [comment]
> * [ ]  I would like to get the buttons better aligned and the info about the stage (see "Stage staging") moved to the top (see: "carts:0.11.1 in staging stage). @ermin-muratovic @laneli @Kirdock, do you have an opinion/improvement on my proposal?
> 
> image

Then we would have two different views in the evaluation screen. Currently we only navigate to a specific stage in the evaluation screen in the bridge, but there is a deep link to show all stages.
I'm fine with the "Back" and "View service" button, but "View stage in sequence" should not be placed here because we could have several stages here. Or we could change "View stage XXX in sequence" and place the needed buttons.

**Comment by Kirdock** [comment]
> * [ ]  Click on "View service" opens wrong stage - I get `prod-customer-a` but expect `staging`
>   image

The thing is, that we can't be sure that this sequence we are looking at the moment is available in the service screen. The latest deployment event could be different than the last evaluation event. In order to have the right functionality we need to change or implement a new deep-link, which selects a deployment via image name

**Comment by ermin-muratovic** [comment]
> * [ ]  I would like to get the buttons better aligned and the info about the stage (see "Stage staging") moved to the top (see: "carts:0.11.1 in staging stage). @ermin-muratovic @laneli @Kirdock, do you have an opinion/improvement on my proposal?

@johannes-b 
As @Kirdock already stated above, the Buttons have different functions. It could happen that we show multiple Heatmaps in this view (from each stage) and there the "View sequence" button should be next to it. With the "View service" button we have a difficulty, but maybe @Kirdock we could load the specific event additionally?

**Comment by Kirdock** [comment]
As discussed with @johannes-b the evaluation screen now looks as follows:
image

**Review by ermin-muratovic — APPROVED** [review]
lgtm

**Pull request merged**
