### PR TITLE
fix: Improve set Git upstream error / success handling (#4374)

### LINKED ISSUE #4374: Setting upstream failed, but the error is not shown in Bridge
Using Keptn 0.8.3,

I added a git upstream in Bridge, but it seems that the API responded with a 500, which is not shown prominently in the UI:

image
image

**Note**: A short toast notification in the bottom-center is shown, but it disappears so quickly, that it is barely noticeable.

Probably related to https://github.com/keptn/keptn/issues/4375

### PR DESCRIPTION
**Pull request by laneli**
Fixes #4374 
Signed-off-by: Elisabeth Lang <elisabeth.lang@dynatrace.com>

image
image

### CODE REVIEW

**Comment by ermin-muratovic** [comment]
Could we align the buttons on the right side? And do we have the same issue with global notifications (new version notification)?

Inked126630051-15999d52-bd34-4ddf-bb5b-34ac659ac60b_LI

**Comment by laneli** [comment]
> Could we align the buttons on the right side? And do we have the same issue with global notifications (new version notification)?

I will check about the globals

**Comment by laneli** [comment]
It's now aligned globally and component-wise. I also updated the hover effect of the icon button, so that it does look a bit more pretty.

image

image

**Review by ermin-muratovic — APPROVED** [review]
lgtm

**Pull request merged**
