### PR TITLE
feat(shipyard-controller): uniform api multiple subscriptions (#4437)

### LINKED ISSUE #4437: Extend Uniform to support subscription management
## Action Item
In [KEP52](https://github.com/keptn/enhancement-proposals/pull/52) the proposal is, the give the user the opportunity to customize subscriptions for a given Keptn Integration. 

To support this use case, the Uniform API needs to be extended to support multiple subscriptions each having its own filter (project, stage,service). Further, a new *general-purpose event* shall be sent (e.g. `sh.keptn.events.subscriptions.changed`, exact naming open) which holds the information about the subscription change of the particular Keptn integration and can be consumed by interested parties. (e.g. distributor of keptn integration)

## Implementation Details
- [ ] Data flow: https://github.com/keptn/keptn/pull/4656#issuecomment-881219643
- [x] Data model: https://github.com/keptn/keptn/pull/4656#issuecomment-883333130

## Acceptance Criteria
As a user, I can use the Uniform API to update subscriptions (including filters) of a Keptn integration. A general-purpose event is emitted by this action.

## Definition of Done
- [ ] existing integration test is enhanced to test this functionality
- [ ]  swagger doc up to date
- [ ] Spec updated (general purpose events section)

### PR DESCRIPTION
**Pull request by warber**
closes #4437 
PR in go-utils: https://github.com/keptn/go-utils/pull/316

This PR extends the uniform API to manage multiple subscriptions for each integration.
Moreover, the project, stage and service property of a subscription filter was changed to be an array of strings instead of a string

``` 
{
    "id": "5064d01dea681b742391298cfbf62ea02fdc8ab8",
    "name": "local-service",
    "metadata": {
      "hostname": "",
      "integrationversion": "",
      "distributorversion": "",
      "location": "remote-execution-plane",
      "kubernetesmetadata": {
        "namespace": "keptn",
        "podname": "",
        "deploymentname": "local-service"
      }
    },
    "subscriptions": [
      {
        "topics": [
          "sh.keptn.event.dev.echo.triggered"
        ],
        "status": "",
        "filter": {
          "project": [
            "project1",
            "project2"
          ],
          "stage": [
            "stage1",
            "stage2"
          ],
          "service": [
            "service1"
          ]
        }
      }
    ]
  }
```

### CODE REVIEW

**Comment by warber** [comment]
Open Question:
Currently, the `IntegrationID` is a composition of name, namespace, project, stage, and service.
Since it is now allowed to have multiple projects, stages and servics these fields were removed from the `IntegrationID`. What should be added additionally to have a unique `IntegrationID`?

**Comment by warber** [comment]
we agreed to take also the `K8S_NODE_NAME` as part of the `IntegrationID`

**Comment by warber** [comment]
Before merging this PR, the bridge needs to be adapted to the changes made in this PR.
Bridge issue: #4572

**Comment by johannes-b** [comment]
After re-thinking the use-cases around that story, I came to the conclusion that separation of subscriptions based on projects is needed. For example, let`s assume we have two projects `musicshop`, `sockshop` and I would like to activate a Keptn-service for stage `dev` in `musicshop and stage `production` in `sockshop`. With the current implementation this would look as follows: 
```
{
    "subscriptions": [
      {
        "topics": [
          "sh.keptn.event.dev.echo.triggered"
        ],
        "status": "",
        "filter": {
          "project": [
            "musicshop",
            "sockshop"
          ],
          "stage": [
            "dev",
            "production"
          ],
          "service": [ ]
        }
      }
    ]
  }
```

Given this configuration, also `dev` in `sockshop` would be activated and `production` for `musicshop`. A configuration that should not exist. 

Consequently, I propose to separate the subscriptions based on projects. Given the above example, it would look as follows: 
```
{
    "subscriptions": [
      {
        "topics": [
          "sh.keptn.event.dev.echo.triggered"
        ],
        "status": "",
        "filter": {
          "project": [
            "musicshop"
          ],
          "stage": [
            "dev"
          ],
          "service": [ ]
        }
      },
      {
        "topics": [
          "sh.keptn.event.dev.echo.triggered"
        ],
        "status": "",
        "filter": {
          "project": [
            "sockshop"
          ],
          "stage": [
            "production"
          ],
          "service": [ ]
        }
      }
    ]
  }
```

From a UI perspective, a service without any subscription for a project will be listed in the table, but marked as `not activated`. Please see here, for more details: https://github.com/keptn/keptn/issues/4436#issuecomment-883184771

**Pull request closed without merging**
