### PR TITLE
feat: Run Jmeter-Service using job executor

### PR DESCRIPTION
**Pull request by TannerGabriel**
## This PR

This PR enables the user to run the `jmeter-service` as a Kubernetes job using the [Job-executor-service](https://github.com/keptn-sandbox/job-executor-service), which reduces the resource usage on the cluster since the `jmeter-service` will only run if a test is triggered. 

### How to test

You can test the implementation by running the [job-executor-service](https://github.com/keptn-sandbox/job-executor-service/pull/63) with the following configuration:

```
apiVersion: v2
actions:
  - name: "Run JMeter"
    events:
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "functional"
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "performance"
    tasks:
      - name: "Run jmeter smoke tests"
        image: "gabrieltanner/jmeter-service:latest"
        workingDir: "/keptn"
        env:
          - name: HOST
            value: "$.data.deployment.deploymentURIsLocal[0]"
            valueFrom: event
          - name: JOB
            value: "true"
            valueFrom: string
          - name: EVENT
            value: "$"
            valueFrom: event
            as: json
```

### CODE REVIEW

**Comment by TannerGabriel** [comment]
To test the functionality yourself, you currently need to run the job-executor-service with the image mentioned in the following [PR](https://github.com/keptn-sandbox/job-executor-service/pull/64). After that, add the following configuration to your service:

```
apiVersion: v2
actions:
  - name: "Run JMeter"
    events:
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "functional"
      - name: "sh.keptn.event.test.triggered"
        jsonpath:
          property: "$.data.test.teststrategy"
          match: "performance"
    tasks:
      - name: "Run jmeter smoke tests"
        image: "gabrieltanner/jmeter-service:latest"
        workingDir: "/keptn"
        env:
          - name: HOST
            value: "$.data.deployment.deploymentURIsLocal[0]"
            valueFrom: event
          - name: JOB
            value: "true"
            valueFrom: string
          - name: EVENT
            value: "$"
            valueFrom: event
            as: json
```

The following command can be used to add the configuration file to your Keptn service:

```
keptn add-resource --project=sockshop --service=carts --stage=staging --resource=jmeter.yaml --resourceUri=job/config.yaml
```

**Comment by jetzlstorfer** [comment]
One test still failing https://github.com/keptn/keptn/pull/4939/checks?check_run_id=3340907266

**Review by christian-kreuzberger-dtx — CHANGES_REQUESTED** [review]
Hi Gabriel, and thanks for the PR and the work done!

As mentioned on Slack, those changes will not be merged into Keptn core, as this PR introduces additional complexity of jmeter-service and reduces maintainability. 

Nevertheless, we will move your changes and the README you created in the PR description into a separate repository.

**Comment by mowies** [comment]
> Nevertheless, we will move your changes and the README you created in the PR description into a separate repository.

@christian-kreuzberger-dtx did this happen already?

**Comment by christian-kreuzberger-dtx** [comment]
We have adapted changes via a different JMeter image. I will close this PR:

**Pull request closed without merging**
