### PR TITLE
test: Enhance backup-restore integration test with git HEAD reset

### LINKED ISSUE #7167: Restore configuration-service does not work when following instructions
**Environment**

* Keptn Version (`keptn version`): `0.13.2`

**Affected Component**

* [x] (Configuration-service) passiv, the bug is in the docs
* [x] Docs

## Describe the bug
When following the instructions for restoring the configuration service according to: https://keptn.sh/docs/0.13.x/operate/backup_and_restore/#restore-configuration-service

I get the following error when executing: 
```
johannes@TAG009442084012:~/keptn-backup$ kubectl cp ./reset-git-repos.sh keptn-migration/$CONFIG_SERVICE_POD:/ -c configuration-service

tar: can't remove old file reset-git-repos.sh: Read-only file system
command terminated with exit code 1
```

* The reason is that the configuration-service provides *write* permissions on the `/data/config` folder only: https://github.com/keptn/keptn/blob/master/installer/manifests/keptn/charts/control-plane/templates/configuration-service.yaml#L100

* The fix is already provided here: https://github.com/keptn/keptn.github.io/pull/1107

**To Reproduce**
* Execute the backup/restore instructions: https://keptn.sh/docs/0.13.x/operate/backup_and_restore/#title

## Definition of Done
- While the fix can be provided via the documentation (please see: https://github.com/keptn/keptn.github.io/pull/1107), I would kindly ask for an integration test of these instructions.

### PR DESCRIPTION
**Pull request by odubajDT**
## This PR

- enahnces backup-restore integration test with reseting git repositorories to HEAD

### Related Issues

Fixes #7167 

### Integration tests
https://github.com/keptn/keptn/actions/runs/1997071748

### CODE REVIEW

**Comment by johannes-b** [comment]
Hi @odubajDT, 
thanks for extending the test!

Do you agree that we should add a comment saying: "When changing this test (especially the reset-get-repos.sh), please update the Keptn documentation for Backup & Restore accordingly." ? (Or is this bad practice?)

**Comment by odubajDT** [comment]
> Hi @odubajDT, thanks for extending the test!
> 
> Do you agree that we should add a comment saying: "When changing this test (especially the reset-get-repos.sh), please update the Keptn documentation for Backup & Restore accordingly." ? (Or is this bad practice?)

Sure no problem :)

**Review by RealAnna — APPROVED** [review]
LGTM

**Comment by odubajDT** [comment]
@johannes-b any other concerns or can we merge ? Please update the docs afterwards according to my comment here https://github.com/keptn/keptn/issues/7167#issuecomment-1070406427

**Comment by johannes-b** [comment]
@odubajDT no. Many thanks for adding the comment to the code! I will take care of the keptn/docs page.

**Pull request merged**
