### PR TITLE
adding CONTRIBUTORS.md file

### PR DESCRIPTION
**Pull request by jetzlstorfer**
To have a holistic overview of all contributors, I've created a file that should list all project contributors and new contributors should add themselves to this file.

Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>

### CODE REVIEW

**Comment by christian-kreuzberger-dtx** [comment]
This is a manual process, which people tend to not follow.
Also, I do not see the advantage over having the GitHub Contributor Page here: https://github.com/keptn/keptn/graphs/contributors

Can you please elaborate?

**Comment by jetzlstorfer** [comment]
The GitHub statistics are fantastic for code contributions, but they do not cover contributions on issues and Keptn Enhancements Proposals. Therefore we want to create a dedicated file to appreciate all contributors.

**Comment by jetzlstorfer** [comment]
Hi @christian-kreuzberger-dtx , I've added a clarification that this list is not intended to be the single source of truth or a realtime maintained list. Instead, the idea of this list is to highlight both code and non-code contributions to the project. 
New contributors should add themselves with their first PR and non-code contributions can be managed in the way that maintainers can add those contributors.

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the clarification. I understand the reasoning of appreciating all contributions, not just code contributions.

However, it is **still a manual process**, which will have an impact on our contributors as well as maintainers (more work involved for everyone), and potentially piss off people that we forgot to mention.

If anyone wants to approve this PR, that's fine with me. But I'm not going to approve it for the reasons stated above.

**Comment by jetzlstorfer** [comment]
I do understand your concerns. Therefore, I mentioned in the CONTRIBUTING.md that this document should be updated whenever someone files his/her first pull request *by the contributor* and not maintained by the maintainers. However, there might be occasions where this will be forgotten, I am aware of that.

**Review by johannes-b — APPROVED** [review]
It is great to see such a long list of contributors to the Keptn project. Nevertheless, I agree with christian-kreuzberger-dtx that maintaining this file effort. I will approve this file for now but revisit it (in a month) to see how it has evolved and to evaluate its effects.

**Comment by jetzlstorfer** [comment]
Thanks for the approval. I think your approach can work!

**Pull request merged**
