### PR TITLE
feat(cli): CLI containerization

### LINKED ISSUE #7586: Provide an official containerized CLI
Currently Keptn ships the CLI executable, but there is no container version for it. It would be great to have one so that it could be used in container environments to interact with Keptn.

Use-cases:

* Using externa Keptn instance, e.g. invoking Keptn sequences from Job Executor service
* Using Keptn CLI as a task in Tekton/GitHub Actions and other containerized automation systems

### PR DESCRIPTION
**Pull request by MdSahil-oss**
## This PR

- adds this new feature

### Related Issues

Fixes #7586

### CODE REVIEW

**Review by mowies — COMMENTED** [review]
Nice job so far! And thanks for your contribution :)
Can you also add the CLI building to the pipelines?
We are building all the artifacts in github actions matrix builds.
you'll need to add the proper env variables at the top of `CI.yml` and `release.yml`.
Also in `gh-actions-scripts/prepare_changed_artifacts.sh` you'll need to add some additional variables, same as the others that are already there.

**Comment by mowies** [comment]
@MdSahil-oss if you say the pipeline work is too much for you, we can also create a follow-up ticket for that and I can take it over :)

**Comment by MdSahil-oss** [comment]
@mowies I will finish the pipeline work very soon myself :)

**Comment by MdSahil-oss** [comment]
@mowies can you have a look on the changes that I made related to codepipeline.

**Comment by mowies** [comment]
@MdSahil-oss thanks for the updates! I will do some final changes and debugging and push them directly to your PR when I'm done and then we can merge this.

**Comment by mowies** [comment]
@MdSahil-oss i found an issue that prevent us from building the CLI in docker. So this PR is blocked by https://github.com/keptn/keptn/issues/9462

**Review by bacherfl — APPROVED** [review]

**Review by mowies — APPROVED** [review]
LGTM! Thanks for your contribution!

**Pull request merged**
