### PR TITLE
chore: Add @robertjahn as member

### PR DESCRIPTION
**Pull request by robertjahn**
## This PR

- adds this new feature

### Related Issues

Fixes #1234523

### CODE REVIEW

**Review by oleg-nenashev — APPROVED** [review]

**Comment by thisthat** [comment]
Hi @robertjahn could you please sign your commit? You can check the instruction here: https://github.com/keptn/keptn/pull/6313/checks?check_run_id=4460246097

**Comment by robertjahn** [comment]
@thisthat  - I will need help with the DCO update.  I tried to adjust and update the head of my fork.

**Comment by oleg-nenashev** [comment]
Hi @robertjahn . Did you have a chance to update the commit to include DCO? FTR there is https://github.com/keptn/community/issues/72for improving contributor experiences

**Comment by robertjahn** [comment]
Closing this PR.  Going to redo as to resolve the merge conflicts I was having

**Pull request closed without merging**
