### PR TITLE
Spell check

### PR DESCRIPTION
**Pull request by jsoref**
This PR adds the [check-spelling action](https://github.com/marketplace/actions/check-spelling) per https://github.com/keptn/keptn/pull/3234#issuecomment-791461647.

See [documentation](https://github.com/check-spelling/check-spelling/wiki).

I'll watch the repo for a while to make sure the landing fairly smooth, after a while, you can just @ me for support.

### CODE REVIEW

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM

**Comment by christian-kreuzberger-dtx** [comment]
Thanks!

**Comment by jetzlstorfer** [comment]
Cool new feature!

**Comment by jsoref** [comment]
You'll want to be a bit careful of PRs that branched before this landed (forcing people to rebase is one approach) as you don't want people to be able to sneak mistakes into the default branch, it leads to confusion for people who branch off from commits with those typos.

**Pull request merged**
