### PR TITLE
#3542 Better sequence visualization when having more than one sequence in a stage

### LINKED ISSUE #3542: Better sequence visualization when having more than one sequence in a stage
The new sequence visualization is great - but - when someone has more than one sequence that gets executed within a stage the bridge doesnt show us which sequence was responsible for which tasks

The following is a screenshot that visualizes this where I have two seqeuences in my testing stage. Would be easier for the user to see the span of a sequence in the bridge as well

image

### PR DESCRIPTION
**Pull request by ermin-muratovic**
The sequences are now also visualized as a tile. This also gives now access to the triggered and finished events of the sequence itself and allows also to check their payload. When having multiple sequences in a stage, you also see the separation of the sequences better and have an overall better view what was going on in which context.

image

Closes #3542

### CODE REVIEW

**Comment by jsoref** [comment]
Fwiw, the next version of check-spelling will ignore two character "words" (but until then, please just add `tt` to `expect.txt` -- either manually or by running the command suggested)

**Review by Kirdock — CHANGES_REQUESTED** [review]
- [ ] In the environment and sequence screen the visualization of an approval changed.

Before:
image

Now:
image

- [ ] Sequence and stage do not represent this status. Stage and sequence icon should be a blue question mark.

image

---

- [ ] Deployment URL and evaluation result is missing now:

Before:
image

Now:
image

---

- [ ] Failed quality gates are missing

Before:
image

Now:
image

**Comment by johannes-b** [comment]
To save one click: 

image

**Comment by johannes-b** [comment]
- [ ] Loading icon for a stage does not work: 

image

**Comment by Kirdock** [comment]
- [ ] Loading icon is still missing,
If evaluation is running:
image
If delivery is running:
image
In Sequence screen:
image
- [ ] Count of "Quality gates failed" is wrong. 
image

- [ ] Approval icon and color is still missing. Icon of the first "delivery" should be blue and a question mark.
image

**Comment by Kirdock** [comment]
- [ ] Loading state of stages in the timeline is not updating correctly
image
image
image

At first it was loading (for "dev") but after the first task finished is was not loading anymore, despite the fact other tasks were running

**Review by Kirdock — APPROVED** [review]
LGTM

**Comment by grabnerandi** [comment]
Thanks for implementing this!!

**Pull request merged**
