### PR TITLE
Add Kitopi to ADOPTERS.md

### PR DESCRIPTION
**Pull request by adriangonciarz**

### CODE REVIEW

**Review by jetzlstorfer — CHANGES_REQUESTED** [review]
link goes to the wrong youtube video

**Comment by jetzlstorfer** [comment]
Please update, e.g., to this one https://keptn.sh/resources/user-adoption/#continuously-evaluating-application-resiliency-with-litmuschaos-locust-and-keptn

**Comment by adriangonciarz** [comment]
fixed

**Review by jetzlstorfer — DISMISSED** [review]
lgtm

**Review by johannes-b — APPROVED** [review]
lgtm

**Review by jetzlstorfer — APPROVED** [review]
lgtm

**Review by johannes-b — APPROVED** [review]

**Comment by jsoref** [comment]
@johannes-b, @jetzlstorfer: I've made #3565 to exclude this file from spell checking.

(I'll be talking about the spell checker today)

**Pull request merged**
