### PR TITLE
#2718 Reduced number of platform tests

### LINKED ISSUE #2718: Reduce number of platform/integration tests on travis-ci
Due to the current limitations of Travis-CI https://github.com/keptn/keptn/issues/2715, we are forced to limit our jobs running on travis-ci.

To start with, I propose that we run less integration tests on different platforms, e.g.:
image

Of this list, I believe we can remove the following integration tests:

* K3s 1.17, 1.18
* MicroK8s 1.17, 1.18
* All Minikube tests (if it works on K3s and MicroK8s, it will most likely also work on Minikube)

This should significantly bring down the required build minutes.

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #2718

### CODE REVIEW

**Review by warber — APPROVED** [review]
lgtm

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM

**Review by christian-kreuzberger-dtx — CHANGES_REQUESTED** [review]
Sorry, I just saw that we still have `minikube_create_cluster.sh`. I think it can be safely deleted now, right?

**Comment by bacherfl** [comment]
> Sorry, I just saw that we still have `minikube_create_cluster.sh`. I think it can be safely deleted now, right?

yes indeed, I will remove that script

**Review by johannes-b — APPROVED** [review]
lgtm

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM

**Pull request merged**
