### PR TITLE
chore: Add StackScribe to CONTRIBUTOR.md

### PR DESCRIPTION
**Pull request by StackScribe**
https://github.com/keptn/community/issues/141

### CODE REVIEW

**Comment by thisthat** [comment]
Hey @StackScribe, thank you for your contributions 🙌 
I see that the `value.yaml` file of this PR is taken from your previous contribution in https://github.com/keptn/keptn/pull/7155
Could you please remove it and solve the conflicts in `CONTRIBUTORS.md`?

**Comment by StackScribe** [comment]
I deleted values.yaml from this PR but github still says I have conflicts that must be resolved but the "Resolve conflicts" button is greyed out.   So I went back to my shell, did a git pull, added a space to the file and pushed it, hoping it would identify conflicts but it doesn't. 

I also can't do a git pull upstream master: `ssh: Could not resolve hostname git: nodename nor servname provided, or not known` .  If I click on "Fork" on github.com, it doesn't seem to know that I have a fork.  So I think I need to blow my clown away and refork but I'd like to get this PR straightened out first.

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
The branch needs to be fixed

**Comment by oleg-nenashev** [comment]
@StackScribe I will close it since there is no progress. Feel free to reopen

**Pull request closed without merging**
