### PR TITLE
#2485 No info or timeout while installing if there aren't enough resources available

### PR DESCRIPTION
**Pull request by Godtide**

### CODE REVIEW

**Comment by johannes-b** [comment]
Hi @Godtide, 
thanks for the PR!
I understand that a timeout makes sense there, but I think that 7sec is too short. 
Is there any special need to set the timeout to 7sec?

**Comment by Godtide** [comment]
Not at all.
How many seconds do you suggest?

**Comment by johannes-b** [comment]
Hi @Godtide,
I think my question was a little bit misleading and pointing in the wrong direction since we should not discuss the duration of the timeout, but rather a solution on getting more information on a failed Helm upgrade. 

In course of working on this issue, could you figure out whether the function: **UpgradeChart** see: https://github.com/keptn/keptn/blob/master/cli/pkg/helm/helm_helper.go#L133
provides more information when a Helm chart upgrade is not possible (maybe due to limited resources)?

**Comment by Godtide** [comment]
https://github.com/keptn/keptn/blob/ca298963e5eac9bc9962a3347ad29751f4a25846/cli/pkg/helm/helm_helper.go#L164-L167
provides info on a failed upgrade

**Comment by christian-kreuzberger-dtx** [comment]
Thanks for the contribution! However, as there is no progress in this PR I'm closing it now.

**Pull request closed without merging**
