### PR TITLE
fix: Graceful shutdown failing test (#6462)

### LINKED ISSUE #6426: Integration tests failed
* Link to run: https://github.com/keptn/keptn/actions/runs/1609650520
* Triggered by: Scheduled build
* Branch: master
* Version: 0.12.0-dev.202112211320
* Datetime: 202112211320
* Commit: e5e508e0

Integration Tests have finished.

| Target Platform        |  Keptn Install    |  Keptn Auth  | Airgapped Images | Log Ingestion   | Log Forwarding   | Sequence States   | Sequence Timeout   | Sequence Control   | Sequence Queue   | Sequence Loop |  QG Standalone  |  Self Healing  |  Del-Assist  |  Backup-Restore  |  User-Man. Depl.  | Cont Deliv | Cont Deliv (Remote Exec) | Manage secrets | Webhook integration | Graceful Shutdown | Uniform Registration   |
| ---------------------- | ----------------- | ------------ | ---------------- | --------------- | ---------------- | ----------------- | ------------------ | ---------------- | ------------------ | ------------- | --------------- | -------------- | ------------ | ---------------- | ----------------- |----------- | ------------------------ | -------------- | ------------------- | ----------------- | ---------------------- |
| kubernetes/GKE 1.19 | success | success | skipped | success | success | success | success | success | success | success | success | success | success | success | success | skipped | success | success | success | :x: **failure** | success |
| kubernetes/GKE 1.21 | success | success | skipped | success | success | success | success | success | success | success | success | success | success | success | success | success | skipped | success | success | :x: **failure** | success |
| kubernetes/k3d-on-GHA v4.4.6 | success | success | success | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped | skipped |
| kubernetes/k3s-on-GHA v1.16.15+k3s1 | success | success | skipped | success | success | success | success | success | success | success | success | success | skipped | skipped | skipped | skipped | skipped | success | success | skipped | success |
| kubernetes/k3s-on-GHA v1.21.1+k3s1 | success | success | skipped | success | success | success | success | success | success | success | success | success | skipped | skipped | skipped | skipped | skipped | success | success | skipped | success |
| openshift/minishift-on-GHA 3.11 | success | success | skipped | success | success | success | success | success | success | success | skipped | success | skipped | skipped | skipped | skipped | skipped | success | success | skipped | skipped |

Note: This issue was auto-generated from [integration_tests.yml](.github/workflows/integration_tests.yml)

### PR DESCRIPTION
**Pull request by RealAnna**
Signed-off-by: RealAnna <anna.reale@dynatrace.com>

Fixes #6426

### CODE REVIEW

**Review by oleg-nenashev — DISMISSED** [review]

**Comment by odubajDT** [comment]
Integration tests run: https://github.com/keptn/keptn/actions/runs/1630554339

**Comment by odubajDT** [comment]
@RealAnna can you please rebase the branch to the current master ? It contains fixes regarding gitea installation. Or are you planning any other changes to this PR? Thank you

**Comment by odubajDT** [comment]
LGTM, but let's wait for the integration tests result: https://github.com/keptn/keptn/actions/runs/1630688578

**Review by odubajDT — APPROVED** [review]

**Comment by odubajDT** [comment]
Test failed :/

**Comment by odubajDT** [comment]
integration tests failed: https://github.com/keptn/keptn/runs/4657448684?check_suite_focus=true

**Review by bacherfl — APPROVED** [review]

**Pull request merged**
