### PR TITLE
#2938 Show task details in sequence details

### PR DESCRIPTION
**Pull request by ermin-muratovic**
Show sequence tasks filtered by stage and show progress details of each task in tiles.

sequence-screen-details-2021-01-28

### CODE REVIEW

**Comment by ermin-muratovic** [comment]
Show sequence tasks filtered by stage and show progress details of each task in tiles.

image

When expanding a task, you see the details (started, finished, message) and the payload of each step.

image

**Comment by Kirdock** [comment]
The result of sequence tasks should be taken from `.finished` instead of `.triggered` traces

**Review by Kirdock — CHANGES_REQUESTED** [review]
There are some issues
- The selected task is not reset after changing the project. The last selected task remains.
- If a task detail has labels, the expand-icon is offset.
image
- It is not possible to send manual approvals. The detail is empty.
image
- If a sequence does not have stages, an image or service name, it's incorrectly displayed
image

**Review by Kirdock — APPROVED** [review]
LGTM

**Pull request merged**
