### PR TITLE
fix(bridge): Fix relative weight calculation (#9099)

### PR DESCRIPTION
**Pull request by Kirdock**
Backport of #9099

### CODE REVIEW

**Comment by thisthat** [comment]
Would it make sense also to add a test that covers the usage of `getRelativeSliWeight`?

**Comment by Kirdock** [comment]
> Would it make sense also to add a test that covers the usage of `getRelativeSliWeight`?

Yes, but then we would need anoher backport to the main branch. This change is something that should have been considered in the original PR.

**Comment by Kirdock** [comment]
> Would it make sense also to add a test that covers the usage of `getRelativeSliWeight`?

Yes, but then we would need anoher backport to the main branch. This change is something that should have been considered in the original PR.

**Comment by thisthat** [comment]
Fair point, this would violate the cherry-picking. Therefore, I would suggest that it is not needed for this PR

**Review by thisthat — APPROVED** [review]

**Pull request merged**
